### ISSUE TITLE
coverage script is failing

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormatConformance#134]
### Summary

`poetry run coverage` fails with 

```
Traceback (most recent call last):
  File "/Users/podborski/Library/Caches/pypoetry/virtualenvs/feature-extractor-toolset-D_UVy041-py3.11/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/podborski/projects/mpeg/FileFormatConformance/src/construct/coverage.py", line 305, in main
    spec["link"] = get_document_status_link(spec["ISO"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/podborski/projects/mpeg/FileFormatConformance/src/common/__init__.py", line 68, in get_document_status_link
    toc = get_document_status_toc()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/podborski/projects/mpeg/FileFormatConformance/src/common/__init__.py", line 59, in get_document_status_toc
    payload = response.json()["payload"]
              ^^^^^^^^^^^^^^^
  File "/Users/podborski/Library/Caches/pypoetry/virtualenvs/feature-extractor-toolset-D_UVy041-py3.11/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
```

### Steps to reproduce

run `poetry run coverage`

**Comment by DenizUgur** [comment]
This might be related to the recent update to the mp4ra.org. In which branch did you encounter this?

**Comment by podborski** [comment]
I think it happens on any branch. Just debugged it. Looks like the it is coming from here.

```python
def get_document_status_toc():
    response = requests.get(DOCUMENT_STATUS_URL, timeout=15)
    if response.status_code != 200:
        logger.critical(f"Failed to get document status: {response.status_code}")
        exit(1)

    payload = response.json()["payload"]
    toc = payload["blob"]["headerInfo"]["toc"]
    return {
        heading["text"]: DOCUMENT_STATUS_URL + f"#{heading['anchor']}"
        for heading in toc
    }
```

`response.json()` fails with `requests.exceptions.JSONDecodeError` see here: https://requests.readthedocs.io/en/latest/user/quickstart/#json-response-content

**Comment by DenizUgur** [comment]
Can you try the following change?

```diff
-MP4RA_BOXES_URL = "https://mp4ra.org/boxes.json"
+MP4RA_BOXES_URL = "https://mp4ra.org/api/boxes"
```

**Comment by DenizUgur** [comment]
Ah I see, GitHub changed the output of markdown requests. I'll create a fix for it.

**Comment by podborski** [comment]
We could also add something like this:

```python
    # Check that the content type is application/json
    if response.headers.get("Content-Type") != "application/json":
        logger.warning(
            f"Get Document Status has incorrect content type: {response.headers.get('Content-Type')}"
        )
        return None

    try:
        payload = response.json()["payload"]
    except requests.exceptions.JSONDecodeError:
        logger.warning("Get Document Status received invalid JSON")
        return None
```

to make sure not to break in future. If no link can be obtained it should still create a coverage report, right?

**Comment by DenizUgur** [comment]
They used to include TOC in a JSON object but now they don't respont to `application/json` anymore. I'll parse the html and extract the TOC.

**Comment by DenizUgur** [comment]
PR is being merged right now
