### ISSUE TITLE
npm run serve failing

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormatConformance#7]
I ran `npm install` in the html folder (no problem)  but have a problem with `npm run serve`:
```
❯ npm run serve

> html@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...ato/oss_code/FileFormatConformance/html/node_modules/eslint-loader/index.js??ref--14-0!/Users/cconcolato/oss_code/FileFormatConformance/html/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/cconcolato/oss_code/FileFormatConformance/html/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
```

**Comment by cconcolato** [comment]
Apparently, changing the node version might suffice https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by cconcolato** [comment]
actually using `export NODE_OPTIONS=--openssl-legacy-provider` fixed it
